### ISSUE TITLE
Regarding hyperparameters for training on UCF-QNRF dataset

### ISSUE THREAD

**Issue by svshivapuja** [cvlab-stonybrook/DM-Count#20]
Hi, Firstly I would like to say that your paper and code are very impressive. Thank you for releasing the code.

The default hyperparameters worked well for NWPU and ShanghaiTech datasets but are giving a bad results (MAE -- 600) for UCF-QNRF. Could you please clarify about this ?

Thanks in advance :)

**Comment by Boyu-Wang** [comment]
Default hyperparameters should work for QNRF dataset as well. Since you are able to make it work for NWPU and ShanghaiTech dataset, you may need to check your data in QNRF. Make sure you preprocess the data. 
MAE of 600 is too large. You may also need to check the network output. Make sure it does not always output 0.

**Comment by svshivapuja** [comment]
Okay ! thanks :)
